// <auto-generated />
using System;
using Afri.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Afri.Migrations
{
    [DbContext(typeof(AFRILEARNContext))]
    [Migration("20260316195659_AddParentToUser")]
    partial class AddParentToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Afri.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UnlockedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Achievem__3214EC0792DE51DD");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Afri.Models.AiinteractionFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiresponseId")
                        .HasColumnType("int")
                        .HasColumnName("AIResponseId");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AIIntera__3214EC07E8C21032");

                    b.HasIndex("AiresponseId");

                    b.ToTable("AIInteractionFeedback");
                });

            modelBuilder.Entity("Afri.Models.Airesponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsValidated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ResponseText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AIRespon__3214EC075CB0CC8C");

                    b.HasIndex("StudentQuestionId");

                    b.ToTable("AIResponses");
                });

            modelBuilder.Entity("Afri.Models.ContentReviewAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AssignedTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__ContentR__3214EC078E549168");

                    b.HasIndex("AssignedTeacherId");

                    b.HasIndex("LessonId");

                    b.ToTable("ContentReviewAssignments");
                });

            modelBuilder.Entity("Afri.Models.CurriculumStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<string>("StandardCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Curricul__3214EC07C9395112");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("CurriculumStandards");
                });

            modelBuilder.Entity("Afri.Models.DownloadedLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DownloadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DownloadedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FileSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSynced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Download__3214EC076D54B3C8");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("DownloadedLessons");
                });

            modelBuilder.Entity("Afri.Models.GradeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GradeLev__3214EC073F6D66D0");

                    b.ToTable("GradeLevels");
                });

            modelBuilder.Entity("Afri.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Institut__3214EC076BF725BE");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Afri.Models.InstitutionSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Institut__3214EC07F5814302");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("InstitutionSubscriptions");
                });

            modelBuilder.Entity("Afri.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRtl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRTL");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Language__3214EC07E3F79A84");

                    b.HasIndex(new[] { "Code" }, "UQ__Language__A25C5AA7A145BE30")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Afri.Models.LeaderboardScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Leaderbo__3214EC0711209BF2");

                    b.HasIndex("StudentId");

                    b.ToTable("LeaderboardScores");
                });

            modelBuilder.Entity("Afri.Models.LearningPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Learning__3214EC07849A2B03");

                    b.ToTable("LearningPaths");
                });

            modelBuilder.Entity("Afri.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDownloadable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Lessons__3214EC0714BFC895");

                    b.HasIndex("TopicId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Afri.Models.LessonTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsHumanValidated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TranslatedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceExplanationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__LessonTr__3214EC07ED10D5C7");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonTranslations");
                });

            modelBuilder.Entity("Afri.Models.OfflineSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SyncDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__OfflineS__3214EC079A7BB571");

                    b.HasIndex("StudentId");

                    b.ToTable("OfflineSyncLogs");
                });

            modelBuilder.Entity("Afri.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07CDD3B493");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Afri.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permissi__3214EC07C92948AA");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Afri.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PassingScore")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Quizzes__3214EC07AC123607");

                    b.HasIndex("TopicId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Afri.Models.QuizOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__QuizOpti__3214EC07549170BA");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("Afri.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Marks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__QuizQues__3214EC0715DB4996");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Afri.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07863B324A");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Afri.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RolePerm__3214EC07D367D4D0");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Afri.Models.StudentAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AchievedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentA__3214EC075351ED77");

                    b.HasIndex("AchievementId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAchievements");
                });

            modelBuilder.Entity("Afri.Models.StudentActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentA__3214EC07D5C0AEF4");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentActivityLogs");
                });

            modelBuilder.Entity("Afri.Models.StudentLearningPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime");

                    b.Property<int>("LearningPathId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentL__3214EC073D7898AE");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentLearningPaths");
                });

            modelBuilder.Entity("Afri.Models.StudentProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeSpentMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC0723B5BCB1");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentProgress");
                });

            modelBuilder.Entity("Afri.Models.StudentQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsVoiceInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentQ__3214EC07A0C070A3");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TopicId");

                    b.ToTable("StudentQuestions");
                });

            modelBuilder.Entity("Afri.Models.StudentQuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentQ__3214EC07F4BD33F0");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("StudentQuizAnswers");
                });

            modelBuilder.Entity("Afri.Models.StudentQuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AttemptDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentQ__3214EC07AE3E42CC");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentQuizAttempts");
                });

            modelBuilder.Entity("Afri.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Subjects__3214EC078A802916");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex(new[] { "Code" }, "UQ__Subjects__A25C5AA7488CB98D")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Afri.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("FeatureFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC07FDEDA5D9");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("Afri.Models.SystemUsageStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveUsers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LessonsAccessed")
                        .HasColumnType("int");

                    b.Property<int?>("QuizzesAttempted")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StatisticDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__SystemUs__3214EC07E0843A5A");

                    b.ToTable("SystemUsageStatistics");
                });

            modelBuilder.Entity("Afri.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Topics__3214EC0785E74B05");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Afri.Models.TopicMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TopicMat__3214EC07");

                    b.HasIndex("TopicId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("TopicMaterials");
                });

            modelBuilder.Entity("Afri.Models.TranslationReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonTranslationId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReviewedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Translat__3214EC077AF74952");

                    b.HasIndex("LessonTranslationId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("TranslationReviewLogs");
                });

            modelBuilder.Entity("Afri.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PreferredLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0715A23734");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PreferredLanguageId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053403A62C3C")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Afri.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserSubs__3214EC07659FDF66");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Afri.Models.AiinteractionFeedback", b =>
                {
                    b.HasOne("Afri.Models.Airesponse", "Airesponse")
                        .WithMany("AiinteractionFeedbacks")
                        .HasForeignKey("AiresponseId")
                        .IsRequired()
                        .HasConstraintName("FK__AIInterac__AIRes__01142BA1");

                    b.Navigation("Airesponse");
                });

            modelBuilder.Entity("Afri.Models.Airesponse", b =>
                {
                    b.HasOne("Afri.Models.StudentQuestion", "StudentQuestion")
                        .WithMany("Airesponses")
                        .HasForeignKey("StudentQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__AIRespons__Stude__7C4F7684");

                    b.Navigation("StudentQuestion");
                });

            modelBuilder.Entity("Afri.Models.ContentReviewAssignment", b =>
                {
                    b.HasOne("Afri.Models.User", "AssignedTeacher")
                        .WithMany("ContentReviewAssignments")
                        .HasForeignKey("AssignedTeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__ContentRe__Assig__5224328E");

                    b.HasOne("Afri.Models.Lesson", "Lesson")
                        .WithMany("ContentReviewAssignments")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK__ContentRe__Lesso__531856C7");

                    b.Navigation("AssignedTeacher");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Afri.Models.CurriculumStandard", b =>
                {
                    b.HasOne("Afri.Models.GradeLevel", "GradeLevel")
                        .WithMany("CurriculumStandards")
                        .HasForeignKey("GradeLevelId")
                        .IsRequired()
                        .HasConstraintName("FK__Curriculu__Grade__57DD0BE4");

                    b.HasOne("Afri.Models.Subject", "Subject")
                        .WithMany("CurriculumStandards")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Curriculu__Subje__56E8E7AB");

                    b.Navigation("GradeLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Afri.Models.DownloadedLesson", b =>
                {
                    b.HasOne("Afri.Models.Lesson", "Lesson")
                        .WithMany("DownloadedLessons")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK__Downloade__Lesso__282DF8C2");

                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("DownloadedLessons")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Downloade__Stude__2739D489");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.InstitutionSubscription", b =>
                {
                    b.HasOne("Afri.Models.Institution", "Institution")
                        .WithMany("InstitutionSubscriptions")
                        .HasForeignKey("InstitutionId")
                        .IsRequired()
                        .HasConstraintName("FK__Instituti__Insti__47A6A41B");

                    b.HasOne("Afri.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("InstitutionSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .IsRequired()
                        .HasConstraintName("FK__Instituti__Subsc__489AC854");

                    b.Navigation("Institution");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Afri.Models.LeaderboardScore", b =>
                {
                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("LeaderboardScores")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Leaderboa__Stude__395884C4");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.Lesson", b =>
                {
                    b.HasOne("Afri.Models.Topic", "Topic")
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK__Lessons__TopicId__628FA481");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Afri.Models.LessonTranslation", b =>
                {
                    b.HasOne("Afri.Models.Language", "Language")
                        .WithMany("LessonTranslations")
                        .HasForeignKey("LanguageId")
                        .IsRequired()
                        .HasConstraintName("FK__LessonTra__Langu__6A30C649");

                    b.HasOne("Afri.Models.Lesson", "Lesson")
                        .WithMany("LessonTranslations")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK__LessonTra__Lesso__693CA210");

                    b.Navigation("Language");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Afri.Models.OfflineSyncLog", b =>
                {
                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("OfflineSyncLogs")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__OfflineSy__Stude__2CF2ADDF");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.Payment", b =>
                {
                    b.HasOne("Afri.Models.Institution", "Institution")
                        .WithMany("Payments")
                        .HasForeignKey("InstitutionId")
                        .HasConstraintName("FK__Payments__Instit__4E53A1AA");

                    b.HasOne("Afri.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Payments__UserId__4D5F7D71");

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Afri.Models.Quiz", b =>
                {
                    b.HasOne("Afri.Models.Topic", "Topic")
                        .WithMany("Quizzes")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK__Quizzes__TopicId__04E4BC85");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Afri.Models.QuizOption", b =>
                {
                    b.HasOne("Afri.Models.QuizQuestion", "Question")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__QuizOptio__Quest__0D7A0286");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Afri.Models.QuizQuestion", b =>
                {
                    b.HasOne("Afri.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK__QuizQuest__QuizI__09A971A2");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Afri.Models.RolePermission", b =>
                {
                    b.HasOne("Afri.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__Permi__403A8C7D");

                    b.HasOne("Afri.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__RoleI__3F466844");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Afri.Models.StudentAchievement", b =>
                {
                    b.HasOne("Afri.Models.Achievement", "Achievement")
                        .WithMany("StudentAchievements")
                        .HasForeignKey("AchievementId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentAc__Achie__3587F3E0");

                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("StudentAchievements")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentAc__Stude__3493CFA7");

                    b.Navigation("Achievement");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.StudentActivityLog", b =>
                {
                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("StudentActivityLogs")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentAc__Stude__5AB9788F");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.StudentLearningPath", b =>
                {
                    b.HasOne("Afri.Models.LearningPath", "LearningPath")
                        .WithMany("StudentLearningPaths")
                        .HasForeignKey("LearningPathId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentLe__Learn__1EA48E88");

                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("StudentLearningPaths")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentLe__Stude__1DB06A4F");

                    b.Navigation("LearningPath");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.StudentProgress", b =>
                {
                    b.HasOne("Afri.Models.Lesson", "Lesson")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentPr__Lesso__236943A5");

                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentPr__Stude__22751F6C");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.StudentQuestion", b =>
                {
                    b.HasOne("Afri.Models.Language", "Language")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("FK__StudentQu__Langu__778AC167");

                    b.HasOne("Afri.Models.Lesson", "Lesson")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK__StudentQu__Lesso__76969D2E");

                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentQu__Stude__73BA3083");

                    b.HasOne("Afri.Models.Subject", "Subject")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentQu__Subje__74AE54BC");

                    b.HasOne("Afri.Models.Topic", "Topic")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__StudentQu__Topic__75A278F5");

                    b.Navigation("Language");

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Afri.Models.StudentQuizAnswer", b =>
                {
                    b.HasOne("Afri.Models.StudentQuizAttempt", "Attempt")
                        .WithMany("StudentQuizAnswers")
                        .HasForeignKey("AttemptId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentQu__Attem__160F4887");

                    b.HasOne("Afri.Models.QuizQuestion", "Question")
                        .WithMany("StudentQuizAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentQu__Quest__17036CC0");

                    b.HasOne("Afri.Models.QuizOption", "SelectedOption")
                        .WithMany("StudentQuizAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("FK__StudentQu__Selec__17F790F9");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Afri.Models.StudentQuizAttempt", b =>
                {
                    b.HasOne("Afri.Models.Quiz", "Quiz")
                        .WithMany("StudentQuizAttempts")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentQu__QuizI__123EB7A3");

                    b.HasOne("Afri.Models.User", "Student")
                        .WithMany("StudentQuizAttempts")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentQu__Stude__114A936A");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Afri.Models.Subject", b =>
                {
                    b.HasOne("Afri.Models.GradeLevel", "GradeLevel")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeLevelId")
                        .IsRequired()
                        .HasConstraintName("FK__Subjects__GradeL__59FA5E80");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("Afri.Models.Topic", b =>
                {
                    b.HasOne("Afri.Models.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Topics__SubjectI__5EBF139D");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Afri.Models.TopicMaterial", b =>
                {
                    b.HasOne("Afri.Models.Topic", "Topic")
                        .WithMany("TopicMaterials")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Afri.Models.User", "UploadedByUser")
                        .WithMany("TopicMaterials")
                        .HasForeignKey("UploadedByUserId")
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Afri.Models.TranslationReviewLog", b =>
                {
                    b.HasOne("Afri.Models.LessonTranslation", "LessonTranslation")
                        .WithMany("TranslationReviewLogs")
                        .HasForeignKey("LessonTranslationId")
                        .IsRequired()
                        .HasConstraintName("FK__Translati__Lesso__6EF57B66");

                    b.HasOne("Afri.Models.User", "ReviewerUser")
                        .WithMany("TranslationReviewLogs")
                        .HasForeignKey("ReviewerUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Translati__Revie__6FE99F9F");

                    b.Navigation("LessonTranslation");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("Afri.Models.User", b =>
                {
                    b.HasOne("Afri.Models.GradeLevel", "GradeLevel")
                        .WithMany("Users")
                        .HasForeignKey("GradeLevelId")
                        .HasConstraintName("FK__Users__GradeLeve__5441852A");

                    b.HasOne("Afri.Models.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .HasConstraintName("FK__Users__Instituti__52593CB8");

                    b.HasOne("Afri.Models.User", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Afri.Models.Language", "PreferredLanguage")
                        .WithMany("Users")
                        .HasForeignKey("PreferredLanguageId")
                        .HasConstraintName("FK__Users__Preferred__534D60F1");

                    b.HasOne("Afri.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__5165187F");

                    b.Navigation("GradeLevel");

                    b.Navigation("Institution");

                    b.Navigation("Parent");

                    b.Navigation("PreferredLanguage");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Afri.Models.UserSubscription", b =>
                {
                    b.HasOne("Afri.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSubsc__Subsc__42E1EEFE");

                    b.HasOne("Afri.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSubsc__UserI__41EDCAC5");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Afri.Models.Achievement", b =>
                {
                    b.Navigation("StudentAchievements");
                });

            modelBuilder.Entity("Afri.Models.Airesponse", b =>
                {
                    b.Navigation("AiinteractionFeedbacks");
                });

            modelBuilder.Entity("Afri.Models.GradeLevel", b =>
                {
                    b.Navigation("CurriculumStandards");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Afri.Models.Institution", b =>
                {
                    b.Navigation("InstitutionSubscriptions");

                    b.Navigation("Payments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Afri.Models.Language", b =>
                {
                    b.Navigation("LessonTranslations");

                    b.Navigation("StudentQuestions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Afri.Models.LearningPath", b =>
                {
                    b.Navigation("StudentLearningPaths");
                });

            modelBuilder.Entity("Afri.Models.Lesson", b =>
                {
                    b.Navigation("ContentReviewAssignments");

                    b.Navigation("DownloadedLessons");

                    b.Navigation("LessonTranslations");

                    b.Navigation("StudentProgresses");

                    b.Navigation("StudentQuestions");
                });

            modelBuilder.Entity("Afri.Models.LessonTranslation", b =>
                {
                    b.Navigation("TranslationReviewLogs");
                });

            modelBuilder.Entity("Afri.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Afri.Models.Quiz", b =>
                {
                    b.Navigation("QuizQuestions");

                    b.Navigation("StudentQuizAttempts");
                });

            modelBuilder.Entity("Afri.Models.QuizOption", b =>
                {
                    b.Navigation("StudentQuizAnswers");
                });

            modelBuilder.Entity("Afri.Models.QuizQuestion", b =>
                {
                    b.Navigation("QuizOptions");

                    b.Navigation("StudentQuizAnswers");
                });

            modelBuilder.Entity("Afri.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Afri.Models.StudentQuestion", b =>
                {
                    b.Navigation("Airesponses");
                });

            modelBuilder.Entity("Afri.Models.StudentQuizAttempt", b =>
                {
                    b.Navigation("StudentQuizAnswers");
                });

            modelBuilder.Entity("Afri.Models.Subject", b =>
                {
                    b.Navigation("CurriculumStandards");

                    b.Navigation("StudentQuestions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Afri.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("InstitutionSubscriptions");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Afri.Models.Topic", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Quizzes");

                    b.Navigation("StudentQuestions");

                    b.Navigation("TopicMaterials");
                });

            modelBuilder.Entity("Afri.Models.User", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ContentReviewAssignments");

                    b.Navigation("DownloadedLessons");

                    b.Navigation("LeaderboardScores");

                    b.Navigation("OfflineSyncLogs");

                    b.Navigation("Payments");

                    b.Navigation("StudentAchievements");

                    b.Navigation("StudentActivityLogs");

                    b.Navigation("StudentLearningPaths");

                    b.Navigation("StudentProgresses");

                    b.Navigation("StudentQuestions");

                    b.Navigation("StudentQuizAttempts");

                    b.Navigation("TopicMaterials");

                    b.Navigation("TranslationReviewLogs");

                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
